[context.production.headers]
  for = "/*"
  [context.production.headers.values]
    ACCESS-CONTROL-ALLOW-ORIGIN = "https://acceptatie.erkenningen.nl"
[context.deploy-preview.headers]
  for = "/*"
  [context.deploy-preview.headers.values]
    ACCESS-CONTROL-ALLOW-ORIGIN = "https://acceptatie.erkenningen.nl"